/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#006972',
        'on-surface': '#191c1d',
        'on-primary-container': '#00535b',
        'on-secondary-fixed-variant': '#574500',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'surface-tint': '#006972',
        'on-tertiary-fixed-variant': '#8b0e45',
        'surface-container-highest': '#e1e3e4',
        'surface-container-high': '#e7e8e9',
        'on-secondary-fixed': '#241a00',
        outline: '#6f797b',
        error: '#ba1a1a',
        'surface-variant': '#e1e3e4',
        background: '#f8f9fa',
        'secondary-fixed': '#ffe087',
        'secondary-container': '#fdd34d',
        'on-secondary-container': '#725b00',
        'on-primary': '#ffffff',
        'on-background': '#191c1d',
        'surface-bright': '#f8f9fa',
        'on-secondary': '#ffffff',
        'tertiary-container': '#ff9fba',
        'on-error': '#ffffff',
        'surface-dim': '#d9dadb',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'primary-fixed': '#92f1fe',
        surface: '#f8f9fa',
        'tertiary-fixed-dim': '#ffb1c5',
        'on-surface-variant': '#3e484a',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      maxWidth: {
        medium: '430px',
      },
    },
  },
  plugins: [],
};
